### ISSUE TITLE
h1 h2 not communicating

### ISSUE THREAD

**Issue by burhanqayoom** [Samruddhi1995/Software-Defined-Networks-#1]
I am running loadbalancing.py as an argument to the ryu-manager and in the other terminal I am running a mininet script having the topology as you have created. 
Then I follow you steps of limiting flow table size and ECMP load balancing.
The hosts are not able to ping.
Moreover, there is no packet transfer as n_packets=0 for s1 s2 s3. S4 shows 2 packets. In addition, there is a message in loadbalacing.py window as shown in the fig. 
What I need to comprehend from all this? 
Similarly, in reactive_controller.py there is no overflow as depicted in one of the figures posted by you.
![Screenshot from 2019-10-26 17-07-54](https://user-images.githubusercontent.com/47428833/67619104-04cc2480-f815-11e9-9464-f395ff8d69a2.png)
![Screenshot from 2019-10-26 17-08-03](https://user-images.githubusercontent.com/47428833/67619105-0564bb00-f815-11e9-9e68-0b19344752d9.png)

**Comment by Zack-Tsang** [comment]
Hi, burhanqayoom! Do you fix it out? I have the same problem with you, if you have fix it out, could you please share with me? Thanks in advance!
